dummy_consultation_table = """| General topic | Subtopic | Sentiment | Group | Number of responses | Revised summary | Topic number |
|:------------------------|:-----------------------------------------|:------------|:--------|----------------------:|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------:|
| Development Support | Redevelopment Of Underused Site | Positive | All | 4 | Redevelopment of long-vacant, poorly maintained,<br>and underused properties is supported to provide<br>much-needed homes close to amenities and to<br>increase weekday footfall on the high street. This<br>revitalization can significantly enhance the<br>street's overall appearance, provided that<br>exterior details such as shop signs and lighting<br>are carefully controlled to prevent visual<br>clutter. <br><br>Additionally, community support<br>is contingent upon certain conditions being met.<br>Specifically, the scale of the deve... | 1 |
| Building Design | Excessive Height And Bulk | Negative | All | 2 | The proposed top storey would be visible above the<br>established roofline of the historic town centre,<br>requiring revisions to its massing to prevent it<br>from dominating the older terraces. Furthermore,<br>the building is out of scale with the neighboring<br>two- and three-storey structures, resulting in an<br>adverse visual impact near the junction. | 2 |
| Community Impact | Loss Of Affordable Meeting Space | Positive | All | 2 | There is strong support for the flexible<br>ground-floor meeting room dedicated to young<br>people, with recommendations to collaborate<br>directly with youth organisations to shape its<br>design, ensure safety, and establish evening<br>hours. Similarly, the proposed community room has<br>received strong backing on the condition that it<br>remains both accessible and affordable for local<br>groups, supported by clear management and booking<br>guidelines to guarantee its ongoing success. | 3 |
| Amenity Impacts | Loss Of Daylight And Sunlight | Negative | All | 1 | Residents opposite the site raise concerns about<br>the loss of daylight, noting that shadow diagrams<br>do not adequately show winter impacts. | 4 |
| Assessment And Planning | Need For Independent Daylight Assessment | Negative | All | 1 | There is a request for an independent daylight and<br>sunlight assessment prior to any decision on the<br>application. | 5 |
| Building Design | Lack Of Upper Floor Setbacks | Negative | All | 1 | The upper floors lack necessary setbacks to<br>mitigate the visual impact of the building's<br>overall height. | 6 |
| Community Impact | Improved Evening Safety And Vibrancy | Positive | All | 1 | Active ground-floor frontages are expected to make<br>the street feel safer and more welcoming during<br>the evening. | 7 |
| Community Impact | Loss Of Affordable Meeting Space | Negative | All | 1 | The development threatens a valued local gathering<br>spot that serves specific community demographics<br>without adequate replacement. | 8 |
| Development Support | Efficient Brownfield Site Utilization | Positive | All | 1 | The project represents a sensible use of a<br>brownfield site that will increase local spending<br>at existing shops. | 9 |
| Local Economy | Displacement Of Existing Local Cafe | Negative | All | 1 | The plans force the closure of an affordable,<br>independently run community meeting space used by<br>older residents and parents. | 10 |
| Local Economy | Provision Of Affordable Commercial Space | Negative | All | 1 | Concerns exist that new commercial rents will be<br>unaffordable for small local businesses,<br>potentially reducing high street diversity by<br>replacing modest premises with expensive units. | 11 |
| Local Economy | Provision Of Affordable Commercial Space | Positive | All | 1 | If permission is granted, space should be reserved<br>for the displaced cafe or another local business<br>at a genuinely affordable rent. | 12 |
| Local Economy | Support For Small Commercial Units | Negative | All | 1 | Independent traders face potential loss of passing<br>trade due to narrowed pavements and construction<br>disruption, requiring measures like business<br>continuity plans and clear pedestrian access. | 13 |
| Local Economy | Support For Small Commercial Units | Positive | All | 1 | Small commercial units are preferred over large<br>chain stores because they provide opportunities<br>for local businesses to occupy the space. | 14 |"""

dummy_consultation_table_zero_shot = """| General topic | Subtopic | Sentiment | Group | Number of responses | Revised summary | Topic number |
|:----------------|:-------------------------------------------------------------|:------------|:--------|----------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------:|
| Not assessed | High-Street Vitality And Town-Centre Regeneration | Positive | All | 3 | Introducing new residential units above active<br>shops is a beneficial strategy to increase weekday<br>footfall and efficiently utilise underutilised<br>land on the high street. Redeveloping these<br>underused sites brings additional spending to<br>existing businesses, while active ground-floor<br>frontages and small commercial units contribute to<br>making the area feel safer and more welcoming. | 1 |
| Not assessed | Housing Affordability And Service Charges | Negative | All | 3 | Concerns have been raised regarding the long-term<br>security of affordability commitments,<br>highlighting the necessity for the prior<br>publication of tenure splits and service charges.<br>Additionally, residents should be exempt from any<br>additional service charges merely for accessing or<br>utilizing the courtyard garden<br>space.<br><br>Further worries focus on the<br>affordability of deposits and service charges for<br>first-time renters and younger residents, with<br>apprehensions that the units will ultimately<br>become ex... | 2 |
| Not assessed | Building Height, Scale And Massing | Negative | All | 2 | The proposed development's top storey and overall<br>building height and bulk are considered out of<br>scale with neighboring properties, disrupting the<br>historic roofline and town centre character.<br>Consequently, there are calls for further<br>revisions to the massing so that the structure<br>does not dominate older terraces, including<br>suggestions that the upper floors be set back and<br>the overall height reduced. | 3 |
| Not assessed | Community Rooms And Bookable Facilities | Positive | All | 2 | There is strong support for the flexible<br>ground-floor meeting space dedicated to young<br>people, with recommendations to collaborate<br>directly with youth organisations regarding its<br>design, safeguarding measures, and evening<br>operating hours. <br><br>Additionally, the<br>proposed community room has been positively<br>received, provided that specific conditions are<br>met. These include establishing affordable booking<br>rates, clear management structures, defined<br>opening hours, and a reliable reservation system<br>to gu... | 4 |
| Not assessed | Affordable Housing Provision | Positive | All | 1 | The inclusion of central affordable homes is<br>welcomed, though commitments must be secured for<br>the long term with transparent service charges and<br>tenure mix. | 5 |
| Not assessed | Biodiversity, Bats And Nesting Birds | Negative | All | 1 | Concerns exist regarding the adequacy of<br>ecological surveys for bats and nesting birds in<br>older roofs and trees, highlighting the need for<br>comprehensive seasonal surveys and pre-demolition<br>mitigation. | 6 |
| Not assessed | Commercial Affordability For Independent Traders | Negative | All | 1 | Viability documents fail to demonstrate that small<br>local businesses can afford new commercial rents,<br>risking high street diversity by replacing modest<br>premises with expensive units. | 7 |
| Not assessed | Construction Noise, Dust And Vibration | Negative | All | 1 | Severe impacts from construction noise, dust, and<br>vibration are anticipated due to the site's close<br>proximity to existing homes and shops,<br>necessitating strict working hour limits and a<br>designated complaints contact. | 8 |
| Not assessed | Daylight, Sunlight And Overshadowing | Negative | All | 1 | Concerns regarding the loss of daylight, with<br>shadow diagrams failing to demonstrate winter<br>impacts, leading to requests for an independent<br>assessment. | 9 |
| Not assessed | Delivery, Servicing And Loading Arrangements | Negative | All | 1 | There is a need for a clear loading plan and<br>restrictions on delivery times to avoid conflicts<br>with school arrival and collection periods. | 10 |
| Not assessed | Development Density And Overdevelopment | Negative | All | 1 | Concerns that the proposed scheme crams too much<br>onto the site, leading to potential issues with<br>overdevelopment, traffic, late-night activity, and<br>loss of privacy. | 11 |
| Not assessed | Electric Vehicle Charging | Positive | All | 1 | Secure basement parking and electric vehicle<br>charging points are welcomed, alongside requests<br>for more disabled spaces and a dedicated car-club<br>bay to reduce private vehicle ownership. | 12 |
| Not assessed | Housing Mix And Family-Sized Homes | Positive | All | 1 | Support expressed for the inclusion of larger<br>family-sized flats and accessible layouts,<br>alongside suggestions to improve internal storage<br>and balcony usability. | 13 |
| Not assessed | Impact On Local Businesses During Construction | Negative | All | 1 | Concerns that construction activity and narrowed<br>pavements will disrupt independent traders and<br>reduce passing trade, requiring clear signage and<br>a business continuity plan. | 14 |
| Not assessed | Local Character And Contextual Design | Negative | All | 1 | Criticism that the proposed design is generic and<br>fails to respond appropriately to local<br>architectural proportions and detailing found on<br>the high street. | 15 |
| Not assessed | Local Character And Contextual Design | Positive | All | 1 | Redevelopment of the long-vacant site is seen as<br>an opportunity to improve the street's appearance<br>using appropriate brick and stone materials. | 16 |
| Not assessed | Local Employment, Apprenticeships And Training | Positive | All | 1 | Support for creating long-term apprenticeships<br>alongside construction jobs, requiring planning<br>conditions for local advertising and reporting on<br>training outcomes. | 17 |
| Not assessed | Loss And Replacement Of The Local Cafe | Negative | All | 1 | The redevelopment causes the loss of a key<br>affordable, independent meeting place used by<br>older residents and parents, with calls for space<br>to be provided at a genuinely affordable rent. | 18 |
| Not assessed | Parking, Disabled Bays And Car-Club Provision | Positive | All | 1 | The inclusion of secure parking is supported,<br>though additional provisions for disabled parking<br>bays and a car-club scheme are recommended to help<br>households avoid owning individual vehicles. | 19 |
| Not assessed | Planning Conditions, Obligations And Long-Term<br>Management | Negative | All | 1 | The need for firmer management conditions and a<br>reduced scheme size to better balance development<br>impacts on nearby residents. | 20 |
| Not assessed | Pressure On School Places | Negative | All | 1 | The development risks increasing pressure on local<br>schools, and the council must ensure adequate<br>educational capacity and developer contributions<br>for family-sized flats. | 21 |
| Not assessed | Privacy, Outlook And Sense Of Enclosure | Negative | All | 1 | The close proximity of the rear wing creates an<br>overbearing outlook and an unacceptable sense of<br>enclosure for neighbouring gardens, which obscure<br>glazing fails to resolve. | 22 |
| Not assessed | Public Amenities And Town-Centre Facilities | Positive | All | 1 | Support for securing practical town-centre<br>benefits like publicly accessible toilets,<br>drinking-water refill points, and bookable meeting<br>spaces through planning permission. | 23 |
| Not assessed | Shopfront Design, Signage And Lighting | Negative | All | 1 | Shop signs and lighting require strict control to<br>prevent visual clutter and maintain an appropriate<br>frontage appearance. | 24 |
| Not assessed | Social-Rent Housing Provision | Positive | All | 1 | Strong support for delivering urgently needed<br>social-rent homes early in the development,<br>ensuring they match the quality and access<br>arrangements of private units. | 25 |
| Not assessed | Sustainable Drainage And Flood Risk | Negative | All | 1 | Concerns that existing drainage struggles during<br>heavy rain, requiring proof that the development<br>and increased hard surfacing will not worsen<br>flooding, backed by lifelong sustainable drainage<br>maintenance. | 26 |
| Not assessed | Traffic Congestion And Highway Capacity | Negative | All | 1 | Existing peak-hour traffic queues are a concern,<br>and the transport statement underestimates the<br>impact of service vehicles, taxis, and delivery<br>vans. | 27 |
| Not assessed | Tree Retention And Replacement Planting | Negative | All | 1 | The removal of mature trees is opposed, as<br>ornamental replacements do not provide equivalent<br>environmental benefits, and sufficient soil depth<br>is required for new native trees. | 28 |
| Not assessed | Usable Communal Green Space And Play Space | Positive | All | 1 | The courtyard garden is welcomed, but it needs to<br>provide functional seating, shade, and play areas<br>rather than purely decorative planting. | 29 |
| Not assessed | Waste Storage And Refuse Collection | Negative | All | 1 | Concerns that the proposed bin storage and<br>collection facilities are inadequate for the scale<br>of the development, risking increased pavement<br>obstruction and conflicts with traffic and<br>pedestrians. | 30 |"""

case_notes_table = """| General topic | Subtopic | Sentiment | Group | Number of responses | Revised summary | Topic number |
|:---------------------|:----------------------------------|:------------|:--------|----------------------:|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------:|
| Mental Health | Hopelessness And Depression | Negative | All | 7 | The student exhibits expressions of emptiness,<br>sadness, occasional hopelessness, a withdrawn<br>demeanor, and decreased class participation,<br>alongside low self-worth, difficulty finding daily<br>motivation, moderate depression, and trouble<br>sleeping. Despite slight improvements on some<br>days, the student continues to struggle with an<br>overall low mood, which has led to discussions<br>about exploring medication alongside therapy.<br>Additionally, sharing deep feelings of<br>hopelessness during a joint therapeutic ... | 1 |
| Mental Health | Feelings Of Isolation | Negative | All | 4 | The individual is exhibiting behavioral changes<br>characterized by an increasing withdrawal from<br>family members, spending extended periods of time<br>alone in their room, and engaging in very limited<br>social interactions. Additionally, they have<br>expressed a deep sense of loneliness and a strong<br>feeling that nobody understands them. | 2 |
| Substance Use | Occasional Substance Use | Negative | All | 4 | The individual admitted to using alcohol following<br>a physical altercation at school, highlighting<br>ongoing concerns regarding their substance<br>involvement. Additionally, occasional substance<br>use was mentioned without specific details, which<br>aligned with the mother's worries about potential<br>substance abuse. | 3 |
| Mental Health | Agitation And Sullenness | Negative | All | 2 | Initially, the individual appeared sullen and<br>avoided eye contact. Later during the office<br>meetings, they exhibited increasing agitation. | 4 |
| Mental Health | Self-Harm | Negative | All | 2 | Visible signs of self-harm were observed on Alex's<br>arms, and Alex admitted to experiencing occasional<br>thoughts of self-harm accompanied by feelings of<br>hopelessness. | 5 |
| Academic Performance | Declining Grades | Negative | All | 1 | Academic struggles and an increase in absences<br>were noted, leading to an initial school meeting. | 6 |
| Attendance | Increased Absences | Negative | All | 1 | Alex showed a rise in school absences alongside<br>dropping grades and social withdrawal. | 7 |
| Family Dynamics | Conflict With Stepfather | Negative | All | 1 | Displayed sudden anger flare-ups when discussing<br>the home environment, specifically regarding the<br>new stepfather. | 8 |
| Family Dynamics | Family Arguments And Late Outings | Negative | All | 1 | The mother reported frequent household arguments,<br>worries about a new peer group, and unauthorized<br>late-night outings. | 9 |
| Mental Health | Hopelessness And Depression | Positive | All | 1 | Initial feedback following the start of a low-dose<br>antidepressant is positive, showing noticeable<br>improvements in the student's mood and energy<br>levels. | 10 |"""

case_notes_table_grouped = """| General topic | Subtopic | Sentiment | Group | Number of responses | Revised summary | Topic number |
|:--------------------|:--------------------|:------------|:---------|----------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------:|
| Physical Health | Substance Misuse | Negative | Alex D. | 5 | Following an incident at school, Alex admitted to<br>using alcohol. Additionally, there are indications<br>of occasional substance use and potential<br>substance abuse that are tied to new peer groups. | 1 |
| Mental Health | Anger | Negative | Alex D. | 3 | Alex exhibited significant frustration and sudden<br>emotional outbursts concerning home life,<br>accompanied by increasing agitation and<br>defensiveness during meetings. Following a<br>physical altercation, these behaviors resulted in<br>a recommendation for Alex to attend an anger<br>management program. | 2 |
| Mental Health | Emotional Distress | Negative | Alex D. | 3 | Alex received a psychiatric diagnosis of<br>Oppositional Defiant Disorder (ODD), which led to<br>the creation of a comprehensive treatment plan.<br>This condition is characterized by a sullen<br>demeanor, declining academic grades, and shared<br>feelings of hopelessness, all of which require<br>ongoing therapy to manage. | 3 |
| Behaviour At School | Behaviour At School | Negative | Alex D. | 2 | Alex was involved in a physical altercation with<br>another student while at school. | 4 |
| Mental Health | Self-Harm | Negative | Alex D. | 2 | Visible signs of self-harm, along with admissions<br>of occasional thoughts involving self-harm, have<br>been observed and reported. These indicators have<br>directly prompted the need for mental health<br>referrals to ensure appropriate support and<br>intervention. | 5 |
| Mental Health | Emotional Distress | Positive | Alex D. | 1 | Alex started attending group therapy and showed<br>slight improvements in behavior. | 6 |
| Mental Health | Social Issues | Negative | Alex D. | 1 | Feelings of isolation, social disconnection, and<br>struggling to connect with peers at school. | 7 |
| Mental Health | Social Issues | Negative | Jamie L. | 5 | Jamie demonstrates significant social withdrawal<br>both at school and at home, characterized by<br>spending extensive time alone, losing interest in<br>hobbies and family activities, and expressing<br>feelings of isolation. Despite these interpersonal<br>challenges, Jamie's academic performance shows<br>slight improvement. To help address the limited<br>social interactions, there is encouragement for<br>Jamie to join school clubs in order to foster<br>greater connection. | 1 |
| Mental Health | Social Issues | Positive | Jamie L. | 2 | Initial feedback from starting on a low dose of an<br>antidepressant has been positive, indicating some<br>improvements in overall mood and energy levels.<br>Additionally, during a joint session where<br>moderate depression was noted, Jamie expressed a<br>positive interest in participating in art therapy<br>as a coping strategy. | 2 |
| Mental Health | Anger | Negative | Jamie L. | 1 | Jamie reported experiencing feelings of emptiness<br>and hopelessness during a school meeting<br>addressing tardiness and decreased class<br>participation. | 3 |"""

case_notes_table_structured_summary = """| Main heading | Subheading | Summary | Group |
|:--------------------|:--------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------|
| Behaviour At School | Behaviour At School | Alex experienced increased absences and declining<br>grades at school, appearing sullen and avoiding<br>eye contact when meeting at school. Additionally,<br>the school reported a physical altercation between<br>Alex and another student, prompting a meeting<br>where Alex displayed high levels of frustration. | Alex D. |
| Mental Health | Anger | Alex displays significant anger-related issues,<br>including sudden outbursts when discussing home<br>life with a new stepfather, high levels of<br>frustration following a physical altercation with<br>another student at school, and increasing<br>aggression at home where Alex acknowledges issues<br>but blames others. These challenges led to<br>recommendations for an anger management program<br>and a formal diagnosis of Oppositional Defiant<br>Disorder (ODD) by a psychiatrist, alongside family<br>counseling and therapy. | Alex D. |
| Mental Health | Social Issues | Alex frequently experiences feelings of isolation,<br>expressing that "no one gets me" at school, and<br>exhibits sullen behavior with avoided eye contact.<br>Additionally, home life is strained by frequent<br>arguments with the mother, concerns regarding new<br>groups of friends, late-night outings, and a<br>difficult relationship with a new stepfather. | Alex D. |
| Physical Health | General | Alex presented with visible signs of self-harm on<br>the arms, becoming defensive when questioned,<br>which prompted an immediate referral to a mental<br>health professional. During a joint session with a<br>therapist, Alex shared feelings of hopelessness<br>and admitted to occasional thoughts of self-harm,<br>leading to recommendations for a comprehensive<br>mental health evaluation and ongoing therapy, as<br>well as a treatment plan involving medication. | Alex D. |
| Physical Health | Substance Misuse | Across multiple reports, concerns regarding<br>substance use are prominent, including Alex<br>mentioning occasional unspecified substance use<br>during a community center meeting, potential signs<br>of substance abuse noted during a home visit, and<br>an admission to using alcohol following a physical<br>altercation at school. This culminated in a formal<br>psychiatric diagnosis of a co-morbid substance use<br>disorder, ongoing concerns despite slight<br>behavioral improvements from group therapy, and<br>discussions regardin... | Alex D. |
| Trends Over Time | Trends Over Time | Across the various sessions and reports, Alex<br>exhibits a progression of escalating challenges<br>involving academic decline, isolation, increasing<br>aggression, anger outbursts, and substance use.<br>Over time, interventions move from initial school<br>and community meetings to family counseling,<br>office check-ins, visible self-harm resulting in<br>mental health referrals, a formal diagnosis of Odd<br>and co-morbid substance use disorder, and<br>ultimately discussions regarding short-term<br>residential treatment, even... | Alex D. |
| Behaviour At School | Behaviour At School | Jamie's school behavior initially involved<br>consistent tardiness and decreased participation<br>in class, accompanied by appearing withdrawn and<br>sad. Later reports indicated that academic<br>performance slightly improved, though social<br>interactions at school remained limited, prompting<br>encouragement to join school clubs or groups to<br>foster peer connections. | Jamie L. |
| Mental Health | Anger | There are no mentions or observations of anger<br>reported across any of the interactions, meetings,<br>or assessments regarding Jamie. | Jamie L. |
| Mental Health | Social Issues | Jamie exhibited significant social challenges,<br>including withdrawal from family activities, a<br>lack of interest in hobbies, spending extensive<br>time alone in the room, feelings of isolation, and<br>limited social interactions at school. Despite<br>encouragement to join school clubs or groups to<br>foster connection, social difficulties persisted<br>alongside depressive symptoms, though<br>interventions like family therapy were suggested<br>to open communication channels. | Jamie L. |
| Physical Health | General | Jamie experienced physical impacts associated with<br>the depressive state, specifically difficulty<br>sleeping, decreased energy levels at times, and<br>somatic or emotional manifestations such as<br>feeling empty, hopeless, and having low<br>self-worth. Physical health was further addressed<br>through medical evaluations, psychiatric<br>consultation resulting in a Major Depressive<br>Disorder (MDD) diagnosis, and the subsequent<br>introduction of a low dose of antidepressant<br>medication with ongoing monitoring. | Jamie L. |
| Physical Health | Substance Misuse | There are no mentions, indications, or concerns<br>regarding substance misuse reported in any of the<br>observations, meetings, or clinical assessments<br>concerning Jamie. | Jamie L. |
| Trends Over Time | Trends Over Time | Throughout the monitoring period, Jamie's<br>condition evolved from initial consistent<br>tardiness, decreased participation, withdrawal,<br>sadness, and feelings of emptiness and<br>hopelessness. Over subsequent meetings, Jamie<br>reported low self-worth, a lack of motivation,<br>feelings of isolation, and difficulty sleeping,<br>while family and school observed limited social<br>interactions and ongoing struggles despite slight<br>improvements in mood on some days. Eventually,<br>following a formal diagnosis of Major Depre... | Jamie L. |"""
